# Generated by Django 4.2.6 on 2023-12-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Модель телефона')),
                ('info', models.CharField(max_length=20, verbose_name='Характеристики')),
                ('price', models.CharField(max_length=20, verbose_name='Цена')),
                ('author', models.CharField(max_length=20, verbose_name='Производитель')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published',
        ),
    ]
