# Generated by Django 4.2.6 on 2023-12-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_phones_remove_news_pub_date_remove_news_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phones',
        ),
    ]
